CREATE TABLE "ot_ext" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_ot" varchar(20) NOT NULL,
  "estado" varchar(20),
  "prioridad" varchar(10),
  "emergencia" boolean,
  "descripcion_problema" text,
  "diagnostico_inicial" text,
  "fecha_apertura" timestamp,
  "fecha_programada" timestamp,
  "fecha_finalizacion" timestamp,
  "fecha_cierre" timestamp,
  "vehiculo_id" int,
  "vehiculo_patente" varchar(10),
  "vehiculo_marca" varchar(50),
  "vehiculo_modelo" varchar(50),
  "vehiculo_estado" varchar(20),
  "taller_id" int,
  "taller_nombre" varchar(100),
  "taller_region" varchar(50),
  "solicitante_id" int,
  "solicitante_nombre" varchar(100),
  "solicitante_email" varchar(100),
  "mecanico_id" int,
  "mecanico_nombre" varchar(100),
  "jefe_taller_id" int,
  "jefe_taller_nombre" varchar(100)
);

CREATE TABLE "inventario_ext" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "taller_id" int,
  "taller_nombre" varchar(100),
  "taller_region" varchar(50),
  "repuesto_id" int,
  "repuesto_sku" varchar(50),
  "repuesto_nombre" varchar(200),
  "unidad" varchar(20),
  "cantidad_disponible" int,
  "nivel_minimo_stock" int,
  "nivel_maximo_stock" int,
  "fecha_ultimo_reabastecimiento" timestamp
);

CREATE TABLE "solicitudes_repuestos_ext" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar(20),
  "cantidad_solicitada" int,
  "urgente" boolean,
  "numero_oc" varchar(50),
  "proveedor" varchar(200),
  "fecha_entrega_estimada" date,
  "ot_id" int,
  "numero_ot" varchar(20),
  "ot_estado" varchar(20),
  "vehiculo_id" int,
  "vehiculo_patente" varchar(10),
  "vehiculo_marca" varchar(50),
  "taller_id" int,
  "taller_nombre" varchar(100),
  "repuesto_id" int,
  "repuesto_sku" varchar(50),
  "repuesto_nombre" varchar(200)
);

CREATE TABLE "entregas_ext" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "direccion" varchar(10),
  "datos_firma" text,
  "fecha_firma" timestamp,
  "condicion_vehiculo" text,
  "lectura_odometro" int,
  "nivel_combustible" varchar(20),
  "ot_id" int,
  "numero_ot" varchar(20),
  "vehiculo_id" int,
  "vehiculo_patente" varchar(10),
  "conductor_id" int,
  "conductor_nombre" varchar(100),
  "recepcionista_id" int,
  "recepcionista_nombre" varchar(100)
);

CREATE TABLE "emergencias_ext" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion_ubicacion" text,
  "latitud" decimal(10,8),
  "longitud" decimal(11,8),
  "eta_minutos" int,
  "diagnostico_inicial" text,
  "nivel_emergencia" varchar(10),
  "fecha_llegada_real" timestamp,
  "ot_id" int,
  "numero_ot" varchar(20),
  "ot_estado" varchar(20),
  "mecanico_id" int,
  "mecanico_nombre" varchar(100)
);

ALTER TABLE "solicitudes_repuestos_ext" ADD FOREIGN KEY ("ot_id") REFERENCES "ot_ext" ("id");

ALTER TABLE "entregas_ext" ADD FOREIGN KEY ("ot_id") REFERENCES "ot_ext" ("id");

ALTER TABLE "emergencias_ext" ADD FOREIGN KEY ("ot_id") REFERENCES "ot_ext" ("id");

ALTER TABLE "solicitudes_repuestos_ext" ADD FOREIGN KEY ("repuesto_id") REFERENCES "inventario_ext" ("repuesto_id");

ALTER TABLE "solicitudes_repuestos_ext" ADD FOREIGN KEY ("taller_id") REFERENCES "inventario_ext" ("taller_id");

ALTER TABLE "entregas_ext" ADD FOREIGN KEY ("vehiculo_id") REFERENCES "ot_ext" ("vehiculo_id");

ALTER TABLE "emergencias_ext" ADD FOREIGN KEY ("mecanico_id") REFERENCES "ot_ext" ("mecanico_id");
