import { IsIn } from 'class-validator';

export class UpdateStatusDto {
  @IsIn(['PENDIENTE','EN_PROCESO','ESPERA_REPUESTOS','LISTO','APROBADO','COMPLETADO','PENDIENTE_AUTORIZACION_SUPERVISOR','PENDIENTE_VERIFICACION'])
  status!: 'PENDIENTE'|'EN_PROCESO'|'ESPERA_REPUESTOS'|'LISTO'|'APROBADO'|'COMPLETADO'|'PENDIENTE_AUTORIZACION_SUPERVISOR'|'PENDIENTE_VERIFICACION';
}
